### ISSUE TITLE
Replace react-sortable-hoc

### ISSUE THREAD

**Issue by nelsonmestevao** [cesium/cesium.link#55]
> This library is no longer actively maintained. It will continue to receive critical security updates, but there are no new features planned. In future versions of React, the [findDOMNode](https://reactjs.org/docs/react-dom.html#finddomnode) method will be deprecated. This method is a critical piece of the architecture of react-sortable-hoc, and the library will stop working in the future when that method is removed from react-dom.

We should use `@dnd-kit/sortable`! Read more [here](https://github.com/clauderic/dnd-kit).

**Comment by joaodiaslobo** [comment]
No longer applicable.
